### ISSUE TITLE
MySQL연동하기

### ISSUE THREAD

**Issue by shinyoung99** [Jvelopproject/back_End#1]
1. 터미널 열고 brew services start mysql을 썼더니 에러 발생(재부팅 했더니 내용 다 지워짐)
2. ==> Successfully started `mysql` (label: homebrew.mxcl.mysql) 이렇게까지 백그라운드에서 실행을 시킨다고 설정하라고 해서 설정 함 
3. vscode에서 연동시키려고 했더니 확장자를 깔고 했음.
4. connect ECONNREFUSED 127.0.0.1:3306 -> 이 error가 계속 발생 
5.  
<img width="1047" alt="스크린샷 2024-08-22 14 47 15" src="https://github.com/user-attachments/assets/81590da1-2d22-46cf-913c-dbd33fb69d90">
에러가 똑같은 에러가 반복 권한을 바꿔주거나 삭제 후 하는 것을 반복
<img width="1512" alt="스크린샷 2024-08-22 14 48 16" src="https://github.com/user-attachments/assets/6d8e33ce-55b4-4e84-affa-525c0900edd6">
vscode에서 확장자를 설치하여 연동하려고 함

확장자로 안되는 거 같아서 직접 mysqlworkbench로 직접연동을 하려고 시도 했지만 그랬을 경우 의존성을 추가하고 불편함이 있고 프론트하는 사람이 이해하기 어려울 거 같아 확장자를 설치해서 보내는 것으로 생각을 함

6. sudo vim /private/etc/hosts -> 호스트번호를 변경하려고 들어가서 ::1 서버 앞에 있는 번호 앞에 #::1 주석처리를 해도 똑같은 에러가 발생

7. CREATE DATABASE my_data;
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
따로 mysqlworkbench랑 연동을 하려고 시도해서 확장자를 설치하고 했는데도 똑같은 오류가 발생 

<img width="1260" alt="스크린샷 2024-08-23 13 14 56" src="https://github.com/user-attachments/assets/856e3ed1-f8ca-42ed-aa0f-99d0f0c35d13">

포트가 문제가 있는 것 같은데 포트 문제가 해결이 되지 않음

**Comment by underlier12** [comment]
먼저 작업 내용 쓸 때 한번 작성한내용 수정하지말고 계속 추가해 신규로

**Comment by underlier12** [comment]
이런식으로

**Comment by underlier12** [comment]
![Image](https://github.com/user-attachments/assets/d0c57a9f-2545-4e1d-b2d1-29ef88b448bc)

이런식으로 터미널에 나온건 이미지로 캡쳐하지말고 복붙해 아니면 일일히 다시 타이핑해야하잖아

**Comment by underlier12** [comment]
삽질하는건 좋은데 왜 자꾸 확장자랑 쿼리를 건드리는지 모르겠어
지금 mysql 구동조차 안되는게 문제 아니야?

확장자는 mysql 구동이 된 이후에 의미가 있는거고

쿼리 또한 구동이 되야 실행이 될텐데 
```
CREATE DATABASE my_data;
CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(50) NOT NULL,
email VARCHAR(100),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
```

**Comment by underlier12** [comment]
> 에러가 똑같은 에러가 반복 권한을 바꿔주거나 삭제 후 하는 것을 반복

이렇게 뭉뚱그려서 말하지말고 같은 에러가 반복될때 어떤 조치를 취했고 어떻게 실행했었는지 커맨드 다 써 아니면 나도 알 방법이 없지

**Comment by underlier12** [comment]
> sudo vim /private/etc/hosts -> 호스트번호를 변경하려고 들어가서 ::1 서버 앞에 있는 번호 앞에 #::1 주석처리를 해도 똑같은 에러가 발생

이건 어떤 문서에 근거해서 이렇게 조치를 하게 되었는지 어떤 효과를 발휘하는지 reference를 링크 걸고 작업해 갑자기 hosts는 왜 건드는거야

**Comment by underlier12** [comment]
> 확장자로 안되는 거 같아서 직접 mysqlworkbench로 직접연동을 하려고 시도 했지만 그랬을 경우 의존성을 추가하고 불편함이 있고 프론트하는 사람이 이해하기 어려울 거 같아 확장자를 설치해서 보내는 것으로 생각을 함

프론트는 걱정할 필요가 없지 어짜피 api만 제공해주기로 한거 아니었어?

**Comment by underlier12** [comment]
chatgpt 답변 다 달아놓고 어떤 방법을 채택했는지 자세히 다 써

이것만 봐도 뭐가 문제인지 바로 보이잖아
```
connect ECONNREFUSED 127.0.0.1:3306 오류는 클라이언트가 MySQL 서버에 연결하려고 했으나 연결이 거부되었음을 의미합니다. 이 오류가 발생할 수 있는 주요 원인은 다음과 같습니다:

MySQL 서버가 실행 중이지 않음: 가장 일반적인 원인은 MySQL 서버가 실행되지 않아서 클라이언트가 연결할 수 없는 경우입니다. 먼저 MySQL 서버가 실행 중인지 확인해보세요.

bash
코드 복사
sudo mysql.server status
서버가 실행 중이지 않다면, 다음 명령어로 서버를 시작할 수 있습니다:

bash
코드 복사
sudo mysql.server start
잘못된 포트: MySQL 서버가 다른 포트에서 실행 중일 수 있습니다. 기본적으로 MySQL은 3306 포트를 사용하지만, 설정이 변경되었거나 다른 인스턴스가 실행 중일 수 있습니다. my.cnf 파일에서 MySQL 서버의 포트를 확인하세요.

방화벽이나 보안 소프트웨어: 방화벽이나 보안 소프트웨어가 포트 3306에 대한 연결을 차단할 수도 있습니다. 이 경우 해당 포트에 대한 접근을 허용해야 합니다.

MySQL 설정 문제: MySQL 설정 파일(my.cnf 또는 my.ini)에 문제가 있을 수 있습니다. 특히, bind-address 설정이 잘못되어 있을 경우 이 오류가 발생할 수 있습니다. bind-address를 127.0.0.1 또는 0.0.0.0으로 설정해보세요.

포트가 이미 사용 중: 만약 포트 3306이 이미 다른 프로세스에 의해 사용 중이라면, MySQL 서버가 해당 포트에서 실행되지 않을 수 있습니다. 이 경우 다음 명령어로 포트 3306을 사용하는 프로세스를 확인할 수 있습니다:

bash
코드 복사
sudo lsof -i :3306
해당 프로세스를 종료하거나, MySQL이 다른 포트에서 실행되도록 설정할 수 있습니다.

위의 원인을 확인하고 해결하면 ECONNREFUSED 오류를 해결할 수 있을 것입니다.
```

**Comment by underlier12** [comment]
보니까 태스크를 크게 잡은것 같다 하나씩 가자
